VisualStudioProject/Kino/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kino.Models;
using Kino.Models.Wraper;
using Microsoft.AspNetCore.Authorization;

namespace Kino.Controllers {
    
    [Authorize]
    public class FilmController : Controller {
        private readonly KinoDatabaseContext _context;

        public FilmController(KinoDatabaseContext context) {
            _context = context;
        }

        // GET: Film
        public async Task<IActionResult> Index() {
            IEnumerable<Film> filmi = await _context.Film.ToListAsync();
            var wrapperList = new List<KolosejWrapper>();

            foreach (var film in filmi) {
                var wrapper = new KolosejWrapper();
                wrapper.Film = film;
                wrapper.ProdukcijskaZalozba =
                    _context.ProdukcijskaZalozba.FirstOrDefault(s => s.IdZalozba == film.IdZalozba);
                wrapper.StarostnaOmejitev =
                    _context.StarostnaOmejitev.FirstOrDefault(s => s.IdOmejitve == film.IdOmejitve);
                wrapper.OsebjeFilma = _context.OsebjeFilma.FirstOrDefault(s => s.IdOsebjeFilma == film.IdOsebjeFilma);

                wrapperList.Add(wrapper);
            }

            return View(wrapperList);
        }

        // GET: Film/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.IdFilm == id);
            if (film == null) {
                return NotFound();
            }

            return View(film);
        }

        // GET: Film/Create
        public async Task<IActionResult> Create() {
            var wrapper = new KolosejWrapper {
                OsebjeFilmaList = await _context.OsebjeFilma.ToListAsync(),
                ZalozbaList = await _context.ProdukcijskaZalozba.ToListAsync(),
                StarostnaOmejitevList = await _context.StarostnaOmejitev.ToListAsync()
            };

            return View(wrapper);
        }

        // POST: Film/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(KolosejWrapper wrapper) {
            if (ModelState.IsValid) {
                _context.Add(wrapper.Film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(wrapper);
        }

        // GET: Film/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var film = await _context.Film.FindAsync(id);
            if (film == null) {
                return NotFound();
            }

            return View(film);
        }

        // POST: Film/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("IdFilm,IdZalozba,IdOmejitve,IdOsebjeFilma,Naslov,Leto,CasTrajanja")]
            Film film) {
            if (id != film.IdFilm) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!FilmExists(film.IdFilm)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(film);
        }

        // GET: Film/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.IdFilm == id);
            if (film == null) {
                return NotFound();
            }

            return View(film);
        }

        // POST: Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var film = await _context.Film.FindAsync(id);
            _context.Film.Remove(film);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id) {
            return _context.Film.Any(e => e.IdFilm == id);
        }
    }
}

VisualStudioProject/Kino/Controllers/KolosejController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Kino.Models;
using Kino.Models.Wraper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace Kino.Controllers {
    public class KolosejController : Controller {
        private readonly KinoDatabaseContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public KolosejController(KinoDatabaseContext context, UserManager<ApplicationUser> userManager) {
            _context = context;
            _userManager = userManager;
        }

        // GET: Kolosej
        [Authorize]
        public async Task<IActionResult> Index() {
            var wrapperList = new List<KolosejWrapper>();
            var currentUser = await _userManager.GetUserAsync(User);

            IEnumerable<Kolosej> koloseji = await _context.Kolosej.ToListAsync();

            foreach (var kolosej in koloseji) {
                if (kolosej.OwnerId != currentUser.Id) {
                    continue;
                }

                var wrapper = new KolosejWrapper();
                wrapper.Kolosej = kolosej;
                wrapper.Naslov = _context.Naslov.FirstOrDefault(s => s.IdNaslov == kolosej.IdNaslov);
                wrapper.Poste = _context.Poste.FirstOrDefault(s => s.StPoste == wrapper.Naslov.StPoste);

                wrapper.StringNaslov = "" + wrapper.Naslov.Ulica + " " + wrapper.Naslov.HisnaSt + ", " +
                                       wrapper.Poste.Kraj + " " + wrapper.Poste.StPoste + "";
                wrapperList.Add(wrapper);
            }

            return View(wrapperList);
        }

        // GET: Kolosej/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var kolosej = await _context.Kolosej
                .FirstOrDefaultAsync(m => m.IdKolosej == id);
            if (kolosej == null) {
                return NotFound();
            }

            return View(kolosej);
        }

        // GET: Kolosej/Create
        public IActionResult Create() {
            return View();
        }

        // POST: Kolosej/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(KolosejWrapper kolosejWrapper) {
            var currentUser = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid) {
                var posta = kolosejWrapper.Poste;
                var naslov = kolosejWrapper.Naslov;
                var kolosej = kolosejWrapper.Kolosej;
                naslov.StPoste = posta.StPoste;

                if (_context.Poste.Find(posta.StPoste) == null) {
                    _context.Add(posta);
                }
                _context.Add(naslov);
                _context.SaveChanges();

                kolosej.IdNaslov = naslov.IdNaslov;
                kolosej.OwnerId = currentUser.Id;
                _context.Add(kolosej);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(kolosejWrapper);
        }

        // GET: Kolosej/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var kolosej = await _context.Kolosej.FindAsync(id);
            if (kolosej == null) {
                return NotFound();
            }

            return View(kolosej);
        }

        // POST: Kolosej/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("IdKolosej,IdNaslov,Ime")] Kolosej kolosej) {
            if (id != kolosej.IdKolosej) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(kolosej);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!KolosejExists(kolosej.IdKolosej)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(kolosej);
        }

        // GET: Kolosej/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var kolosej = await _context.Kolosej
                .FirstOrDefaultAsync(m => m.IdKolosej == id);
            if (kolosej == null) {
                return NotFound();
            }

            return View(kolosej);
        }

        // POST: Kolosej/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var kolosej = await _context.Kolosej.FindAsync(id);
            _context.Kolosej.Remove(kolosej);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KolosejExists(int id) {
            return _context.Kolosej.Any(e => e.IdKolosej == id);
        }


        public IActionResult Chose(int? id) {
            if (id == null) {
                return NotFound();
            }

            HttpContext.Session.SetInt32("IdKolosej", (int) id);

            return RedirectToAction("Index", "Dvorana");

            //throw new NotImplementedException();
        }
    }
}

VisualStudioProject/Kino/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kino</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Kolosej" asp-action="Index">Kolosej</a></li>
                    <li><a asp-area="" asp-controller="Predstava" asp-action="Index">Predstave</a></li>
                    <li><a asp-area="" asp-controller="Film" asp-action="Index">Filmi</a></li>
                    <li><a asp-area="" asp-controller="Tehnologija" asp-action="Index">Tehnologije</a></li>
                    <li><a asp-area="" asp-controller="ProdukcijskaZalozba" asp-action="Index">Založbe</a></li>
                    <li><a asp-area="" asp-controller="OsebjeFilma" asp-action="Index">Režiserji</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <br />
    <br />

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Simon Korosec, Urban Jagodic</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>